
SELECT t.title, t.rank FROM (
    SELECT 
        books.title,
        RANK () OVER (
            ORDER BY COUNT(borrowing.physicalid) DESC
        ) as rank 
    FROM resources
    INNER JOIN borrowing ON borrowing.physicalid = resources.physicalid
    INNER JOIN books ON books.bookid = resources.bookid
    INNER JOIN genre ON genre.bookid = books.bookid
    WHERE genre.genre = 'RomCom' 
    GROUP BY books.title
) AS t WHERE t.rank <= 5;